from enum import StrEnum
from typing import Literal


TrafficLightValue = Literal["Red", "Amber", "Green", "Blue"]
FinalFieldStatusValue = Literal["PROVIDED", "EXPLICITLY_NONE", "LEFT_BLANK"]


class SchemaField(StrEnum):
    QUARTER = "quarter"
    TRAFFIC_LIGHT = "traffic_light"
    PROGRESS_PERCENT = "progress_percent"
    KEY_SUCCESS = "key_success"
    KEY_CHALLENGE = "key_challenge"
    SUPPORT_NEEDED = "support_needed"

    @property
    def label(self):
        return self.value.replace("_", " ").capitalize()


class ReportedStatus(StrEnum):
    STATED = "STATED"
    EXPLICITLY_NONE = "EXPLICITLY_NONE"
    NOT_MENTIONED = "NOT_MENTIONED"
    UNRESOLVED = "UNRESOLVED"


class FieldStatus(StrEnum):
    EXTRACTED = "EXTRACTED"
    EXPLICITLY_NONE = "EXPLICITLY_NONE"
    MISSING = "MISSING"
    AMBIGUOUS = "AMBIGUOUS"


class Verdict(StrEnum):
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    NEEDS_ATTENTION = "NEEDS_ATTENTION"
    REJECTED = "REJECTED"


class RejectionReason(StrEnum):
    EMPTY_INPUT = "EMPTY_INPUT"
    TOO_SHORT = "TOO_SHORT"
    INPUT_TOO_LARGE = "INPUT_TOO_LARGE"
    UNSUPPORTED_AUDIO_FORMAT = "UNSUPPORTED_AUDIO_FORMAT"
    NO_SPEECH = "NO_SPEECH"
    TRANSCRIPTION_UNAVAILABLE = "TRANSCRIPTION_UNAVAILABLE"
    EXTRACTION_UNAVAILABLE = "EXTRACTION_UNAVAILABLE"
    EXTRACTION_INVALID = "EXTRACTION_INVALID"
    EXTRACTION_REFUSED = "EXTRACTION_REFUSED"
    NOT_A_QUARTERLY_UPDATE = "NOT_A_QUARTERLY_UPDATE"


class FlagCode(StrEnum):
    NOT_STATED = "NOT_STATED"
    UNRESOLVED_CONFLICT = "UNRESOLVED_CONFLICT"
    INVALID_QUARTER = "INVALID_QUARTER"
    YEAR_NOT_STATED = "YEAR_NOT_STATED"
    VOCAB_NORMALISED = "VOCAB_NORMALISED"
    VOCAB_UNMAPPABLE = "VOCAB_UNMAPPABLE"
    NO_NUMERIC_VALUE = "NO_NUMERIC_VALUE"
    OUT_OF_RANGE = "OUT_OF_RANGE"
    NON_INTEGER = "NON_INTEGER"
    RANGE_UNCOMMITTED = "RANGE_UNCOMMITTED"
    APPROXIMATE = "APPROXIMATE"
    RANGE_GIVEN = "RANGE_GIVEN"
    CONVERTED_FROM_WORDS = "CONVERTED_FROM_WORDS"
    TOO_LONG = "TOO_LONG"
    SELF_CORRECTED = "SELF_CORRECTED"
    MACHINE_TRANSLATED = "MACHINE_TRANSLATED"
    EVIDENCE_NOT_FOUND = "EVIDENCE_NOT_FOUND"
    POSSIBLE_INJECTION = "POSSIBLE_INJECTION"
    LOW_TRANSCRIPT_CONFIDENCE = "LOW_TRANSCRIPT_CONFIDENCE"
    TRANSCRIPT_QUALITY_UNAVAILABLE = "TRANSCRIPT_QUALITY_UNAVAILABLE"
